# Modules
[module]
  # Version
  [module.hugoVersion]
    extended = true
    min = '0.110.0' # If changed, update theme.toml

  # Bootstrap
  [[module.imports]]
    path = 'github.com/twbs/bootstrap'
  [[module.imports.mounts]]
    source = 'scss/'
    target = 'assets/scss/bootstrap/'
  [[module.imports.mounts]]
    source = 'dist/js/'
    target = 'assets/js/bootstrap/'
  # Bootstrap RFS
  [[module.imports]]
    path = 'github.com/twbs/rfs'
  [[module.imports.mounts]]
    source = 'scss.scss'
    target = 'assets/scss/bootstrap/vendor/_rfs.scss'

  # Lucide Icons
  [[module.imports]]
    path = 'github.com/lucide-icons/lucide'
  [[module.imports.mounts]]
    source = 'icons/'
    target = 'assets/icons/lucide/'
  # Simple Icons
  [[module.imports]]
    path = 'github.com/simple-icons/simple-icons'
  [[module.imports.mounts]]
    source = 'icons/'
    target = 'assets/icons/simple/'

# Build
[build]
  # PostCSS
  writeStats = true
