# Info
baseURL = 'https://shock.aao.fyi/'
languageCode = 'en'
title = 'Shock'
description = 'Shock Hugo framework.'
copyright = 'aao.fyi'

# Theme
# Replace 'gitlab.com' with 'github.com' if error loading
theme = 'gitlab.com/aao-fyi/shock'

# Features
disableHugoGeneratorInject = false
disableKinds = []
enableGitInfo = true
enableRobotsTXT = true

# Minify
[minify]
  minifyOutput = true

# Module
[module]
  # Version
  [module.hugoVersion]
    extended = true
    min = '0.110.0'

# Parameters
[params]
  # Bootstrap JS
  bootstrapJS = true
  # PostCSS
  postCSS = false
  # Copyright
  copyrightStart = ''
  license = ''
  # Navbar
  navbarBrandLogo = false
  navbarBrandText = true
  navbarFixedTop = true
  # Footer
  footerState = true
  # Manifest
  manifestJSON = true
  manifestColorBG = '#333'

# Menus
[menu]
  [menu.main]
    identifier = 'rss'
    name = 'RSS'
    url = '/index.xml'
  [menu.main]
    identifier = 'sitemap'
    name = 'Sitemap'
    url = '/sitemap.xml'

# Privacy
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = true
  [privacy.twitter]
    disable = true
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = true
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = true
    privacyEnhanced = true

# Services
[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true
